package service

import (
	"context"
	"fmt"
	"io"
	"kzhikcn/pkg/config"
	"kzhikcn/pkg/data"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

type mockRepo struct{}

func (m *mockRepo) OpenAsset(string, string) (io.ReadWriteCloser, error) { return nil, nil }
func (m *mockRepo) RemoveAsset(string, string) error                     { return nil }
func (m *mockRepo) ListAssets(string) ([]string, error)                  { return nil, nil }
func (m *mockRepo) HasAsset(string, string) (bool, error)                { return false, nil }
func (m *mockRepo) ContentReader(string) (io.ReadCloser, error)          { return nil, nil }
func (m *mockRepo) ContentWriter(string) (io.WriteCloser, error)         { return nil, nil }
func (m *mockRepo) Remove(string) error                                  { return nil }

var testDB *gorm.DB

func TestMain(m *testing.M) {
	config.LoadConfig(strings.NewReader(""))

	err := data.ConnectDatabase("sqlite", ":memory:")
	if err != nil {
		panic(err)
	}

	testDB = data.DB()
	testDB.AutoMigrate(&data.Article{}, &data.Category{}, &data.Tag{}, &data.ArticleTag{})

	code := m.Run()

	sqlDB, _ := testDB.DB()
	sqlDB.Close()
	os.Exit(code)
}

func cleanDB(t *testing.T) {
	t.Helper()
	testDB.Exec("DELETE FROM article_tags")
	testDB.Exec("DELETE FROM articles")
	testDB.Exec("DELETE FROM tags")
	testDB.Exec("DELETE FROM categories")
}

func newTestService() *ArticleService {
	ctx := &ServiceContext{
		Conf: &config.Config{},
		Repo: &mockRepo{},
		DB:   testDB,
	}
	return NewArticleService(ctx, nil)
}

func newTestCategory(t *testing.T, name string) *data.Category {
	t.Helper()
	c := &data.Category{CategoryName: name}
	data.DB().Create(c)
	return c
}

func ptr[T any](v T) *T { return &v }

func TestCreate_ValidArticle(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	cat := newTestCategory(t, "go")

	input := &ArticleUpdateFields{
		Title:         ptr("Hello World"),
		Category:      ptr(cat.CategoryName),
		Tags:          []string{"go", "tutorial"},
		Description:   ptr("a test article"),
		EnableComment: ptr(true),
	}

	article, err := svc.Create(ctx, input)
	require.NoError(t, err)
	assert.NotNil(t, article)
	assert.Equal(t, "Hello World", article.Title)
	assert.Equal(t, "go", article.Category.CategoryName)
	assert.Len(t, article.Tags, 2)
	assert.Equal(t, "a test article", article.Description)
	assert.True(t, article.EnableComment)
}

func TestCreate_MinimalArticle(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	input := &ArticleUpdateFields{
		Title: ptr("Minimal Article"),
	}

	article, err := svc.Create(ctx, input)
	require.NoError(t, err)
	assert.NotNil(t, article)
	assert.Equal(t, "Minimal Article", article.Title)
	assert.Equal(t, data.ARTICLE_STATUS_DRAFT, article.Status)
}

func TestCreate_CategoryNotFound(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	input := &ArticleUpdateFields{
		Title:    ptr("Test"),
		Category: ptr("nonexistent"),
	}

	_, err := svc.Create(ctx, input)
	assert.ErrorIs(t, err, ErrCategoryNotFound)
}

func TestCreate_WithNilFields(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	input := &ArticleUpdateFields{
		Title: ptr("Nil Fields"),
	}

	article, err := svc.Create(ctx, input)
	require.NoError(t, err)
	assert.Equal(t, "Nil Fields", article.Title)
	assert.NotEmpty(t, article.CustomID) // auto-generated by GORM BeforeCreate
	assert.False(t, article.EnableComment)
	assert.Equal(t, "", article.Description)
}

func TestCreate_TriggersHooks(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	var beforeCalled, afterCalled bool
	svc.hooks.BeforeCreate = []func(ctx context.Context, article *ArticleUpdateFields) error{
		func(ctx context.Context, a *ArticleUpdateFields) error {
			beforeCalled = true
			return nil
		},
	}
	svc.hooks.AfterCreate = []func(ctx context.Context, article *data.Article) error{
		func(ctx context.Context, a *data.Article) error {
			afterCalled = true
			return nil
		},
	}

	_, err := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Hook Test")})
	require.NoError(t, err)
	assert.True(t, beforeCalled)
	assert.True(t, afterCalled)
}

func TestUpdate_TitleAndDescription(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{
		Title:       ptr("Original"),
		Description: ptr("old desc"),
	})

	updated, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Title:       ptr("Updated"),
		Description: ptr("new desc"),
	})
	require.NoError(t, err)
	assert.Equal(t, "Updated", updated.Title)
	assert.Equal(t, "new desc", updated.Description)
}

func TestUpdate_StatusToPublished(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{
		Title:  ptr("Draft Article"),
		Status: ptr(data.ARTICLE_STATUS_DRAFT),
	})

	updated, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Status: ptr(data.ARTICLE_STATUS_PUBLISHED),
	})
	require.NoError(t, err)
	assert.Equal(t, data.ARTICLE_STATUS_PUBLISHED, updated.Status)
	assert.NotNil(t, updated.PublishedAt)
}

func TestUpdate_Tags(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Tag Test")})

	updated, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Tags: []string{"alpha", "beta"},
	})
	require.NoError(t, err)
	assert.Len(t, updated.Tags, 2)
}

func TestUpdate_CategoryByName(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	newTestCategory(t, "science")
	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Cat Test")})

	updated, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Category: ptr("science"),
	})
	require.NoError(t, err)
	assert.Equal(t, "science", updated.Category.CategoryName)
}

func TestUpdate_CategoryByID(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	newTestCategory(t, "other")
	cat := newTestCategory(t, "math")
	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Cat ID Test")})

	updated, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Category: ptr(fmt.Sprintf("#%d", cat.ID)),
	})
	require.NoError(t, err)
	require.NotNil(t, updated.CategoryID)
	assert.Equal(t, cat.ID, *updated.CategoryID)
}

func TestUpdate_ArticleNotFound(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	_, err := svc.Update(ctx, "00000000-0000-0000-0000-000000000000", ArticleUpdateFields{
		Title: ptr("Nope"),
	})
	assert.ErrorIs(t, err, ErrArticleNotFound)
}

func TestUpdate_CategoryNotFound(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Test")})

	_, err := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Category: ptr("nonexistent"),
	})
	assert.ErrorIs(t, err, ErrCategoryNotFound)
}

func TestDelete_SoftDelete(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("To Delete")})

	err := svc.Delete(ctx, article.ID.String(), false)
	require.NoError(t, err)

	_, err = data.GetArticleById(article.ID.String(), data.LimitQueryModifier(1))
	assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
}

func TestDelete_HardDelete(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Hard Delete")})

	err := svc.Delete(ctx, article.ID.String(), true)
	require.NoError(t, err)

	_, err = data.GetArticleById(article.ID.String(),
		func(tx *gorm.DB) *gorm.DB { return tx.Unscoped().Limit(1) })
	assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
}

func TestDelete_ArticleNotFound(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	err := svc.Delete(ctx, "00000000-0000-0000-0000-000000000000", false)
	assert.ErrorIs(t, err, ErrArticleNotFound)
}

func TestRestore(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{Title: ptr("To Restore")})
	svc.Delete(ctx, article.ID.String(), false)

	err := svc.Restore(ctx, []string{article.ID.String()})
	require.NoError(t, err)

	restored, err := data.GetArticleById(article.ID.String(), data.LimitQueryModifier(1))
	require.NoError(t, err)
	assert.Equal(t, "To Restore", restored.Title)
}

func TestRestore_EmptyIDs(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	err := svc.Restore(ctx, []string{})
	assert.NoError(t, err)
}

func TestIncrementViews(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{
		Title:  ptr("Views Test"),
		Status: ptr(data.ARTICLE_STATUS_PUBLISHED),
	})

	views, err := svc.IncrementViews(ctx, article.ID.String())
	require.NoError(t, err)
	assert.Equal(t, 1, views)

	views, err = svc.IncrementViews(ctx, article.ID.String())
	require.NoError(t, err)
	assert.Equal(t, 2, views)
}

func TestIncrementLikes(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{
		Title:  ptr("Likes Test"),
		Status: ptr(data.ARTICLE_STATUS_PUBLISHED),
	})

	likes, err := svc.IncrementLikes(ctx, article.ID.String())
	require.NoError(t, err)
	assert.Equal(t, 1, likes)

	likes, err = svc.IncrementLikes(ctx, article.ID.String())
	require.NoError(t, err)
	assert.Equal(t, 2, likes)
}

func TestIncrementViews_ArticleNotFound(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	_, err := svc.IncrementViews(ctx, "00000000-0000-0000-0000-000000000000")
	assert.ErrorIs(t, err, ErrArticleNotFound)
}

func TestListArticles_Pagination(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	for i := 0; i < 15; i++ {
		svc.Create(ctx, &ArticleUpdateFields{Title: ptr("Article")})
	}

	articles, total, err := svc.GetArticles(ctx, GetArticlesOptions{
		Page:    1,
		Limit:   10,
		OrderBy: "createdAt",
	}, func(tx *gorm.DB) *gorm.DB { return tx })
	require.NoError(t, err)
	assert.Len(t, articles, 10)
	assert.Equal(t, int64(15), total)
}

func TestListArticles_OrderBy(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	svc.Create(ctx, &ArticleUpdateFields{Title: ptr("A")})
	svc.Create(ctx, &ArticleUpdateFields{Title: ptr("B")})
	svc.Create(ctx, &ArticleUpdateFields{Title: ptr("C")})

	articles, _, err := svc.GetArticles(ctx, GetArticlesOptions{
		Page:    1,
		Limit:   10,
		OrderBy: "createdAt",
	}, func(tx *gorm.DB) *gorm.DB { return tx })
	require.NoError(t, err)
	require.GreaterOrEqual(t, len(articles), 3)
	assert.Equal(t, "A", articles[0].Title)
	assert.Equal(t, "B", articles[1].Title)
	assert.Equal(t, "C", articles[2].Title)
}

func TestUpdate_PublishedAtOnlyOnce(t *testing.T) {
	cleanDB(t)
	svc := newTestService()
	ctx := context.Background()

	article, _ := svc.Create(ctx, &ArticleUpdateFields{
		Title:  ptr("Publish Once"),
		Status: ptr(data.ARTICLE_STATUS_DRAFT),
	})

	updated, _ := svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Status: ptr(data.ARTICLE_STATUS_PUBLISHED),
	})
	firstPublished := updated.PublishedAt

	svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Status: ptr(data.ARTICLE_STATUS_DRAFT),
	})
	updated, _ = svc.Update(ctx, article.ID.String(), ArticleUpdateFields{
		Status: ptr(data.ARTICLE_STATUS_PUBLISHED),
	})

	assert.True(t, firstPublished.Equal(*updated.PublishedAt))
}
